<?php
// compliments.php
function random_compliment() {
  $c = [
    "🌟 Nice one! Your brain is in engineer mode today.",
    "🧠 Clean work! That was a very ‘software engineer’ finish.",
    "✨ Great job — you kept going like a pro.",
    "🚀 You’re leveling up fast. Keep it up!",
    "😼 That was smooth. You understood more than you think.",
    "💡 Solid attempt! Your logic is getting sharper.",
    "🏆 Respect! You handled the exam pressure well.",
    "🔥 Nice! Your effort is giving ‘top student’ energy.",
    "🌈 Good work — practice like this makes you unstoppable.",
    "🐣 Cute win! You finished the whole exam. That’s discipline!",
    "🛠️ Engineer mindset unlocked. Well done!",
    "📈 You’re improving — and it shows!",
    "🧩 Strong focus. Your future self will thank you.",
    "🎯 Great accuracy vibe. Keep practicing!",
    "😺 Proud of you! That was a solid run.",
    "💪 Good grind — that’s how skills grow.",
    "⭐ Nice! You’re closer to mastery than you think.",
    "🧃 Smooth finish! You kept your momentum.",
    "🧠💥 Brain power! You did great.",
    "🍀 Lucky? No... that was hard work. Good job!",
    "🚀 Keep soaring! Your progress is inspiring.",
    "🌟 Stellar effort! You’re shining bright.",
    "🛡️ You’ve got this! Confidence looks good on you.",
    "✨ Keep sparkling! You're doing fantastic.",
    "🔥 Burning bright! Keep that fire alive.",
    "🎉 Celebration time! You deserve it.",
    "🙌 Awesome! That was a flawless performance.",
    "👏 Well done! Your dedication is paying off.",
    "🌟 You're on fire! Keep the momentum going.",
    "🦄 Unique and talented — just like your work.",
    "💥 Explosive progress! Keep it up.",
    "🎖️ You’re a champion! That effort counts.",
    "🌻 Bright future ahead! Keep planting those seeds.",
    "🧙‍♂️ You’re casting magic with your skills!",
    "🔑 You’ve unlocked new levels of understanding.",
    "🌞 Shine on! Your effort lights the way.",
    "🐉 Fierce and focused! Great determination.",
    "🌪️ You’re a whirlwind of productivity.",
    "🧭 Staying on course! Excellent focus.",
    "🎁 Gifted effort! Keep unwrapping success.",
    "🛡️ Strong and steady — stay resilient!",
    "🥇 Gold star! You earned it.",
    "🌺 Blooming brilliance! Keep growing.",
    "🎩 Magic touch! Your work is impressive.",
    "🦸‍♂️ Super effort! You’re a hero in the making.",
    "🌟 Star performer! Keep shining.",
    "🏹 Bullseye! Precision and focus are working.",
    "🚁 Soaring high! Your skills are elevating.",
    "🌍 World-class effort! Keep exploring your potential.",
    "🦅 Free as a bird! Soaring with confidence.",
    "💎 You’re shining like a gem.",
    "🌌 Infinite potential! Keep reaching for the stars.",
    "🧙‍♀️ Wizardry skills! That was magical.",
    "🎸 Rocking that exam! Keep the rhythm going.",
    "🛫 Taking off! Your journey is just beginning.",
    "🌊 Waves of progress! Keep riding high.",
    "🦋 Beautiful transformation! Keep evolving.",
    "🌟 Bright ideas! Keep those sparks flying.",
    "🧗 Climbing higher! Great perseverance.",
    "🧚‍♀️ Sprinkling success! Keep spreading your magic.",
    "🎈 Up, up, and away! Keep ascending.",
    "🐾 Leaving footprints of greatness.",
    "🪄 A touch of brilliance! Keep shining.",
    "🎤 Taking the stage! Show your talent.",
    "🦄 One of a kind! Your work is special.",
    "🌟 A shining example! Keep leading by example.",
    "🧚‍♂️ Enchanting effort! Keep captivating us.",
    "🦅 Flying high! Your potential is limitless.",
    "💫 Shooting for the stars! Keep aiming high.",
    "🌟 Bright as the morning sun! Keep shining bright.",
    "🚴‍♂️ Pedaling forward! Keep moving ahead.",
    "🎯 Hitting the mark! Excellent focus.",
    "🌻 Radiating positivity! Keep that vibe.",
    "💥 Boom! Another great achievement.",
    "🎩 Hat’s off! Excellent work.",
    "🦸‍♀️ Super effort! You’re a real hero.",
    "🌈 Colorful and bright! Keep adding vibrance to your work.",
    "🧚‍♂️ Magical progress! Keep enchanting us.",
    "🚀 Launching into success! Keep ascending.",
    "🌠 Shooting star! Keep shining your light.",
    "🧠 Brainiac! You’re on top of your game.",
    "🎉 Party time! Celebrate your success.",
    "🛡️ Fortified with knowledge! Keep building.",
    "🌟 Radiant star! Keep glowing.",
    "🚁 Helicopter view! Great overview and understanding.",
    "🎯 Precise and perfect! Keep aiming true.",
    "🌞 Brightening your path! Keep moving forward.",
    "🧙‍♂️ Wizard-level skills! Keep practicing the magic.",
    "🦄 Truly unique! Keep standing out.",
    "🌟 Celestial performance! Keep reaching for the stars.",
    "🌊 Making waves! Keep creating ripples of success.",
    "🧚‍♀️ Sparkling achievement! Keep shining bright."
  ];
  return $c[array_rand($c)];
}
?>